<?php
$estados = array();
array_push($estados,"");
array_push($estados,"AC");
array_push($estados,"AP");
array_push($estados,"AM");
array_push($estados,"PA");
array_push($estados,"RO");
array_push($estados,"RR");
array_push($estados,"TO");
array_push($estados,"AL");
array_push($estados,"BA");
array_push($estados,"CE");
array_push($estados,"MA");
array_push($estados,"PB");
array_push($estados,"PE");
array_push($estados,"PI");
array_push($estados,"RN");
array_push($estados,"SE");
array_push($estados,"ES");
array_push($estados,"MG");
array_push($estados,"RJ");
array_push($estados,"SP");
array_push($estados,"PR");
array_push($estados,"RS");
array_push($estados,"SC");
array_push($estados,"DF");
array_push($estados,"GO");
array_push($estados,"MT");
array_push($estados,"MS");

?>